### ISSUE TITLE
Gulp-Sass errors out when entering npm install command

### ISSUE THREAD

**Issue by theREALaltoid** [metamarcdw/mmweb#1]
When entering command "sudo npm install" I'm given the following output:

> node-sass@4.8.3 install /home/zach/nwweb/node_modules/node-sass
> node scripts/install.js

Unable to save binary /home/zach/nwweb/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/home/zach/nwweb/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/home/zach/nwweb/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/home/zach/nwweb/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/home/zach/nwweb/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/home/zach/nwweb/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/zach/nwweb/node_modules/node-sass/vendor' }

> node-sass@4.8.3 postinstall /home/zach/nwweb/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/zach/nwweb/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/zach/nwweb/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.12.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.12.0
gyp verb command install [ '8.12.0' ]
gyp verb install input version string "8.12.0"
gyp verb install installing version: 8.12.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.12.0
gyp verb build dir attempting to create "build" dir: /home/zach/nwweb/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/zach/nwweb/node_modules/node-sass/build'
gyp ERR! System Linux 4.4.0-130-generic
gyp ERR! command "/usr/bin/node" "/home/zach/nwweb/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/zach/nwweb/node_modules/node-sass
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN bootstrap@4.1.1 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.8.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zach/.npm/_logs/2018-09-13T04_00_42_452Z-debug.log

**Comment by theREALaltoid** [comment]
I'm on Linux Mint 18.3

**Comment by metamarcdw** [comment]
Hey I found you!
I believe that this is the belongs in this repo:
https://github.com/metamarcdw/nwweb

Would you mind opening a new issue there? @theREALaltoid
